name: Java CI

on:
  watch:
    types: [ started ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Validate gradlew integrity
      uses: gradle/wrapper-validation-action@v1
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/gradle-wrapper.properties') }}
    - name: Build with Gradle
      run: ./gradlew pmdMain build
    - name: PMD report
      uses: jwgmeligmeyling/pmd-github-action@v1
      if: failure()
      with:
        path: '**/reports/pmd/main.xml'
    - name: Stop Gradle
      run: |
        ./gradlew --stop
    - name: Calculate artifact names
      id: calculate_artifact_names
      run: |
        VERSION=$(awk -F '=' '/^version/ { print $2; }' build.properties)
        BUILD=$(awk -F '=' '/build_number/ { print $2; }' build.properties)
        echo "forge=build/libs/Quark-${VERSION}-${BUILD}.jar" >> "$GITHUB_OUTPUT"
    - name: Sign jars
      env:
        SIGNING_KEY: ${{ secrets.VIOLET_MOON_SIGNING_KEY }}
      if: ${{ env.SIGNING_KEY != '' }}
      run: |
        echo "${SIGNING_KEY}" | gpg --import -
        gpg --local-user "Violet Moon Signing Key" --armor \
          --detach-sign ${{ steps.calculate_artifact_names.outputs.forge }}

    - name: Upload JAR file
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: build/libs/*jar
